### ISSUE TITLE
magnetize crashing server. 

### ISSUE THREAD

**Issue by kalethemonster** [Luligabi1/Incantationem#9] opened 2022-04-09 07:31 UTC
hey, was playing on my aternos server that has incantationem on it, and i walked into an area where a mob that presumably has enchanted armour was loaded in in a cave or sumthing, and it caused the server to crash, even after i restarted it, when i logged in it crashed straqight away. after restarting the server and loggin in multiple times and looking at the logs each time, i can confirm that it is magnetize. here is the link to the error message https://pastebin.com/tJ8rZUFZ

**Comment by Luligabi1** [comment] 2022-05-18 19:42
Hey, sorry for the delay. Unfortunately I wasn't able to find anything on the log to go by to try find the cause; I'll keep this open for now but it'll be nearly impossible to find what's causing the issue without a more descriptive crash log :(

**Comment by Luligabi1** [comment] 2024-06-16 00:14
Closing this as most of the code has been rewritten for 1.21. If you can reproduce this on 1.21, please open a new issue

**Closed as completed by Luligabi1** 2024-06-16 00:14 UTC
Labels: bug
